# Generated by Django 5.0.1 on 2026-02-02 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('logs_analyzed', models.IntegerField(help_text='Number of log chunks analyzed')),
                ('time_window_start', models.DateTimeField(blank=True, help_text='Start of log time window analyzed', null=True)),
                ('time_window_end', models.DateTimeField(blank=True, help_text='End of log time window analyzed', null=True)),
                ('threats_found', models.IntegerField(default=0, help_text='Number of threats detected')),
                ('duration_seconds', models.FloatField(help_text='Time taken for analysis')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Approximate tokens sent to LLM', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is error')),
                ('llm_model_used', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_interval_seconds', models.IntegerField(default=60, help_text='How often to run threat analysis (in seconds)')),
                ('max_logs_per_analysis', models.IntegerField(default=1000, help_text='Maximum number of log chunks to retrieve per analysis')),
                ('log_file_path', models.CharField(default='/var/log/nginx/access.log', help_text='Path to the log file to monitor', max_length=500)),
                ('log_format', models.CharField(choices=[('clf', 'Common Log Format'), ('combined', 'NCSA Combined/Extended')], default='clf', help_text='Log format type', max_length=50)),
                ('chunking_strategy', models.CharField(choices=[('fixed_size', 'Fixed Size (N logs per chunk)'), ('time_window', 'Time Window (logs within N seconds)')], default='time_window', help_text='How to group logs into chunks', max_length=20)),
                ('chunk_size', models.IntegerField(default=100, help_text='For fixed_size: number of logs per chunk')),
                ('chunk_window_seconds', models.IntegerField(default=10, help_text='For time_window: seconds per chunk')),
                ('llm_model', models.CharField(choices=[('mistral:7b-instruct', 'Mistral 7B Instruct')], default='mistral:7b-instruct', help_text='Ollama model name for threat analysis', max_length=100)),
                ('embedding_model', models.CharField(choices=[('nomic-embed-text', 'Nomic Embed Text')], default='nomic-embed-text', help_text='Ollama embedding model for RAG', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable automatic analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='ThreatAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('threat_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('ddos', 'DDoS/DoS Attack'), ('sql_injection', 'SQL Injection'), ('path_traversal', 'Path Traversal'), ('reconnaissance', 'Reconnaissance/Scanning'), ('bot', 'Malicious Bot Activity'), ('other', 'Other Threat')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], db_index=True, default='medium', max_length=20)),
                ('confidence', models.FloatField(help_text='LLM confidence score (0.0-1.0)')),
                ('description', models.TextField(help_text='LLM-generated description of the threat')),
                ('evidence', models.JSONField(help_text='Log entries that triggered the alert')),
                ('recommendation', models.TextField(help_text='Suggested remediation action')),
                ('source_ips', models.JSONField(default=list, help_text='List of source IP addresses involved')),
                ('target_paths', models.JSONField(default=list, help_text='List of targeted paths/endpoints')),
                ('acknowledged', models.BooleanField(default=False, help_text='Has this alert been reviewed?')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Analyst notes')),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='engine.analysisrun')),
            ],
            options={
                'verbose_name': 'Threat Alert',
                'verbose_name_plural': 'Threat Alerts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
