# Generated by Django 5.0.1 on 2026-02-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='embedding_model',
            field=models.CharField(choices=[('nomic-embed-text', 'Nomic Embed Text (2K context)'), ('mxbai-embed-large', 'Mixedbread AI Embed Large (512 context)')], default='nomic-embed-text', help_text='Ollama embedding model for RAG', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='llm_model',
            field=models.CharField(choices=[('mistral:7b-instruct', 'Mistral 7B Instruct (8K context)'), ('qwen2.5:7b-instruct', 'Qwen 2.5 7B Instruct (32K context)'), ('llama3.1:8b-instruct', 'Llama 3.1 8B Instruct (128K context)'), ('qwen2.5:14b-instruct', 'Qwen 2.5 14B Instruct (32K context)'), ('llama3.1:70b-instruct-q4_K_M', 'Llama 3.1 70B Instruct Quantized (128K context)')], default='mistral:7b-instruct', help_text='Ollama model name for threat analysis', max_length=100),
        ),
    ]
