# Generated by Django 5.0.1 on 2026-02-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_config_embedding_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='embedding_model',
            field=models.CharField(choices=[('nomic-embed-text', 'Nomic Embed Text (2K context)'), ('bge-m3', 'BGE M3 (8K context)')], default='nomic-embed-text', help_text='Ollama embedding model for RAG', max_length=100),
        ),
    ]
