# Generated by Django 5.0.1 on 2026-02-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_alter_config_embedding_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='chunk_window_seconds',
        ),
        migrations.AlterField(
            model_name='config',
            name='chunk_size',
            field=models.IntegerField(default=20, help_text='Maximum number of logs per chunk (controls context size)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='chunking_strategy',
            field=models.CharField(choices=[('intelligent', 'Intelligent (group by status codes & IPs) ⭐'), ('fixed_size', 'Fixed Size (sequential grouping)')], default='intelligent', help_text='How to group logs into chunks', max_length=20),
        ),
    ]
