# Generated by Django 5.0.1 on 2026-02-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_remove_config_chunk_window_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='filter_static_assets',
            field=models.BooleanField(default=True, help_text='Exclude static assets (CSS, JS, images) from analysis'),
        ),
    ]
