# Generated by Django 5.0.1 on 2026-02-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_config_filter_static_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='excluded_extensions',
            field=models.TextField(default='.css,.js,.jpg,.jpeg,.png,.gif,.webp,.svg,.ico,.woff,.woff2,.ttf,.eot,.otf,.map,.json,.xml,.mp4,.webm,.mp3,.wav,.zip,.pdf,.doc,.docx', help_text='Comma-separated list of file extensions to exclude (e.g., .css,.js,.png)'),
        ),
    ]
