# Generated by Django 5.0.1 on 2026-02-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_config_excluded_extensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='chunk_size',
        ),
        migrations.RemoveField(
            model_name='config',
            name='chunking_strategy',
        ),
        migrations.RemoveField(
            model_name='config',
            name='embedding_model',
        ),
        migrations.AddField(
            model_name='config',
            name='buffer_size',
            field=models.IntegerField(default=50, help_text='Number of logs to accumulate before analysis (hardcoded intelligent grouping)'),
        ),
        migrations.AddField(
            model_name='config',
            name='context_embedding_model',
            field=models.CharField(choices=[('bge-m3', 'BGE M3 (8K context, best quality)'), ('nomic-embed-text', 'Nomic Embed Text (2K context)')], default='bge-m3', help_text='Large context model for groups and summaries', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='fast_embedding_model',
            field=models.CharField(choices=[('mxbai-embed-large', 'Mxbai Embed Large (512 context, fast)'), ('nomic-embed-text', 'Nomic Embed Text (2K context)')], default='mxbai-embed-large', help_text='Fast model for embedding individual logs immediately', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='rag_time_window_minutes',
            field=models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (120, '2 hours')], default=30, help_text='Time window for RAG context retrieval'),
        ),
        migrations.AddField(
            model_name='config',
            name='vectordb_retention_minutes',
            field=models.IntegerField(default=60, help_text='TTL for embeddings in ChromaDB (minutes). Old embeddings are auto-deleted.'),
        ),
    ]
