# Generated by Django 5.0.1 on 2026-02-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_alter_config_context_embedding_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='llm_model',
            field=models.CharField(choices=[('mistral:7b-instruct', 'Mistral 7B Instruct (8K context) - 4.4GB'), ('qwen2.5:7b-instruct', 'Qwen 2.5 7B Instruct (32K context) - 4.7GB'), ('llama3.1:8b', 'Llama 3.1 8B (128K context) - 4.9GB'), ('qwen2.5:14b-instruct', 'Qwen 2.5 14B Instruct (128K context) - 9.0GB ⭐'), ('llama3.1:8b-instruct-q8_0', 'Llama 3.1 8B Instruct Q8.0 (128K context) - 8.5GB')], default='mistral:7b-instruct', help_text='Ollama model name for threat analysis', max_length=100),
        ),
    ]
