# Generated by Django 5.0.1 on 2026-02-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_alter_config_context_embedding_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='excluded_status_codes',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of status codes to exclude (e.g., 200,301,304 to focus on errors). Leave empty to include all.'),
        ),
        migrations.AddField(
            model_name='config',
            name='excluded_user_agents',
            field=models.TextField(blank=True, default='googlebot,bingbot,msnbot,slurp,duckduckbot,baiduspider,yandexbot,facebookexternalhit,twitterbot,linkedinbot,whatsapp,telegrambot', help_text='Comma-separated list of user agent substrings to exclude (case-insensitive, e.g., googlebot,bingbot). Leave empty to disable.'),
        ),
    ]
