# Generated by Django 5.0.1 on 2026-02-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_config_excluded_status_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='excluded_methods',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of HTTP methods to exclude (e.g., HEAD,OPTIONS). Leave empty to include all methods.'),
        ),
        migrations.AddField(
            model_name='config',
            name='included_methods_override',
            field=models.TextField(blank=True, default='POST,PUT,DELETE,PATCH', help_text='HTTP methods to ALWAYS include, even if their status code is excluded (e.g., POST to catch spam submissions with 200 OK). Overrides status code filtering.'),
        ),
    ]
