# Generated by Django 5.0.1 on 2026-02-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_config_excluded_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='excluded_paths',
            field=models.TextField(blank=True, default='/nodeviewcount,/analytics,/api/tracking,/api/metrics,/heartbeat,/health,/ping', help_text='Comma-separated list of path substrings to exclude (e.g., /nodeviewcount,/api/tracking). Matches if path CONTAINS any of these. Use for legitimate app endpoints.'),
        ),
    ]
