# Generated by Django 5.0.1 on 2026-03-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_config_excluded_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='context_embedding_model',
            field=models.CharField(choices=[('bge-m3', 'BGE M3 (1024 dims, 8K context) - 1.2 GB ⭐ ✓'), ('nomic-embed-text', 'Nomic Embed Text (768 dims, 2K context) - 274 MB ✓'), ('snowflake-arctic-embed2:568m', 'Snowflake Arctic 2 (1024 dims) - 1.2 GB ✓')], default='bge-m3', help_text='Context embedding model for groups/summaries. (Model 3 of 3: base LLM + fast + this.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='fast_embedding_model',
            field=models.CharField(choices=[('mxbai-embed-large', 'Mxbai Embed Large (1024 dims, fast) - 669 MB ⭐ ✓'), ('nomic-embed-text', 'Nomic Embed Text (768 dims) - 274 MB ✓'), ('snowflake-arctic-embed:335m', 'Snowflake Arctic (1024 dims) - 669 MB ✓')], default='mxbai-embed-large', help_text='Fast embedding model for individual logs. (Model 2 of 3: base LLM + this + context.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='llm_model',
            field=models.CharField(choices=[('mranv/siem-llama-3.1:v1', 'SIEM Llama 3.1 v1 (SIEM-tuned) - 4.7 GB ✓'), ('OpenNix/wazuh-llama-3.1-8B-v1:latest', 'Wazuh Llama 3.1 8B v1 (Wazuh-tuned) - 4.7 GB ✓'), ('mistral:7b-instruct', 'Mistral 7B Instruct (8K context) - 4.4 GB ✓'), ('qwen2.5:7b-instruct', 'Qwen 2.5 7B Instruct (32K context) - 4.7 GB ✓'), ('llama3.1:8b', 'Llama 3.1 8B Base (128K context) - 4.9 GB ✓'), ('llama3.1:8b-instruct-q8_0', 'Llama 3.1 8B Instruct Q8 (128K context) - 8.5 GB ✓'), ('qwen2.5:14b-instruct', 'Qwen 2.5 14B Instruct (32K context) - 9.0 GB ⭐ ✓'), ('llama3.1:70b-instruct-q4_K_M', 'Llama 3.1 70B Instruct Q4 (128K context) - 42 GB ✓')], default='qwen2.5:14b-instruct', help_text='Base LLM for threat analysis. System uses 3 models total: 1 base LLM (this) + 2 embedding models (fast + context).', max_length=100),
        ),
    ]
