# Generated by Django 5.0.1 on 2026-03-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_alter_config_context_embedding_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='context_embedding_model',
            field=models.CharField(choices=[('bge-m3', 'BGE M3 (1024 dims, 8K context) - 1.2 GB ✓'), ('nomic-embed-text', 'Nomic Embed Text (768 dims, 2K context) - 274 MB ✓'), ('snowflake-arctic-embed2:568m', 'Snowflake Arctic 2 (1024 dims) - 1.2 GB ✓')], default='bge-m3', help_text='Context embedding model for groups/summaries. (Model 3 of 3: base LLM + fast + this.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='fast_embedding_model',
            field=models.CharField(choices=[('mxbai-embed-large', 'Mxbai Embed Large (1024 dims, fast) - 669 MB ✓'), ('nomic-embed-text', 'Nomic Embed Text (768 dims) - 274 MB ✓'), ('snowflake-arctic-embed:335m', 'Snowflake Arctic (1024 dims) - 669 MB ✓')], default='mxbai-embed-large', help_text='Fast embedding model for individual logs. (Model 2 of 3: base LLM + this + context.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='llm_model',
            field=models.CharField(choices=[('mistral:7b-instruct', 'Mistral 7B Instruct - 4.4 GB'), ('qwen2.5:7b-instruct', 'Qwen 2.5 7B Instruct - 4.7 GB'), ('llama3.1:8b', 'Llama 3.1 8B Base - 4.9 GB'), ('llama3.1:8b-instruct-q8_0', 'Llama 3.1 8B Instruct Q8 - 8.5 GB'), ('codellama:13b', 'Code Llama 13B'), ('qwen2.5:14b-instruct', 'Qwen 2.5 14B Instruct - 9.0 GB'), ('deepseek-r1:14b', 'DeepSeek R1 14B'), ('llama3.1:70b-instruct-q4_K_M', 'Llama 3.1 70B Instruct Q4 - 42 GB'), ('athene-v2:latest', 'Athene v2 - 47 GB')], default='qwen2.5:14b-instruct', help_text='Base LLM for threat analysis. System uses 3 models total: 1 base LLM (this) + 2 embedding models (fast + context).', max_length=100),
        ),
    ]
